name: Deploy FrontEnd to 0xp.marceauclavel.com

on:
  push:
    branches:
      - dev
    paths: 
      - 'front-angular/**'

jobs:
    deploy:

      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version:
            - 14.12

      steps:

      - uses: actions/checkout@v2

      - name: Sets up SSH Agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_MARCEAU }}
      - name: Add server to known_hosts
        run: ssh -o StrictHostKeyChecking=no github@marceauclavel.com
        #run: ssh-copy-id github@marceauclavel.com

      - name: Sets up Node environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Build & Deploy FrontEnd
        run: cd front-angular && npm run deploy-marceau